name: WardenAuth
version: '${project.version}'
main: dev.justjustin.wardenauth.initialization.SpigotAuth
api-version: 1.16
authors: [ JustJustin ]
description: Auth Plugin for offline-mode servers, and auto-premium-mode for Premiums
website: https://github.com/MrUniverse44/WardenAuth
